#Application
api_baseurl=http://localhost:80
api_version=/openmrs/ws/rest/v1
#waitings
max_retry_amounts=5
timeout_mills=1000

#Admin (should be in env or GitHub secret)
admin_username=admin
admin_password=Admin123

#Seeded TestData
patient_identifier_source_uuid=8549f706-7e85-4c1d-9424-217d50a2988b
patient_identifier_type_uuid=05a29f94-c0ed-11e2-94be-8c13b969e334
test_location_uuid=44c3efb0-2583-4c80-a79e-1f756a03c0a1
weight_concept_id=5089AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
height_concept_id=5090AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
encounter_vitals_type_uuid=67a71486-1a54-468f-ac3e-7091a9a79584
test_appointment_kind =Scheduled
test_patient_uuid=81b2c55c-822b-431c-8bb5-917ef870df35
test_visit_type_uuid=7b0f5697-27e3-40c4-8bae-f4049abfb4ed
test_appointment_service_uuid=4ec5c4fe-cfe0-48ff-9e4d-2f201078feae
concept_id=5089AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
time_zone=Europe/Moscow
date_time_format=yyyy-MM-dd'T'HH:mm:ss.SSSZ

consultation_encounter_type_uuid=dd528487-82a5-4082-9c72-ed246bd49591
encounter_provider_uuid=705f5791-07a7-44b8-932f-a81f3526fc98
clinician_encounter_role_uuid=240b26f9-dd88-4172-823d-4a8bfeb7841f
