#Application
api_baseurl=http://localhost:4111
api_version=/api/v1/
api_version_backend=with_fraud_check_with_approve
#DB
db_url=jdbc:postgresql://localhost:5433/nbank
db_username=postgres
db_password=postgres
#Users
admin_username=admin
admin_password=admin
#SelenoidSetup
remote_host=http://localhost:4444/wd/hub
#forRemoteLaunch
ui_baseurl=http://frontend
#forLocalLaunch
#ui_baseurl=http://localhost:3000
browser=chrome
resolution=1920x1080
enable_vnc=true
enable_log=true
enable_recording_video=false
headless_mode=true
#waitings
max_retry_amounts=5
timeout_mills=1000
#wiremock
wire_mock_host=localhost
wire_mock_port=8089
wire_mock_timeout=2000
wire_mock_endpoint=/fraud-check
