#Application
api_baseurl=http://localhost:80
api_version=/openmrs/ws/rest/v1
#waitings
max_retry_amounts=5
timeout_mills=1000

#Admin (should be in env or GitHub secret)
admin_username=admin
admin_password=Admin123

#Seeded TestData
patient_identifier_source_uuid=8549f706-7e85-4c1d-9424-217d50a2988b
patient_identifier_type_uuid=05a29f94-c0ed-11e2-94be-8c13b969e334
test_location_uuid=44c3efb0-2583-4c80-a79e-1f756a03c0a1
weight_concept_id=5089AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
height_concept_id=5090AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
encounter_vitals_type_uuid=67a71486-1a54-468f-ac3e-7091a9a79584
