AppointmentCreateRequest=AppointmentResponse:patientUuid=STANDARD_EQUALS:patient.uuid,serviceUuid=STANDARD_EQUALS:service.uuid,startDateTime=DATE_EQUALS,endDateTime=DATE_EQUALS,appointmentKind=STANDARD_EQUALS,locationUuid=STANDARD_EQUALS:location.uuid,dateAppointmentScheduled=DATE_EQUALS
VisitUpdateRequest=VisitCreateResponse:stopDatetime=DATE_EQUALS
