# Prepared OpenMRS runtime configuration for test environment

admin.password.locked=false
auto_update_database=true

connection.driver_class=com.mysql.jdbc.Driver
connection.password=openmrs
connection.url=jdbc\:mysql\://db\:3306/openmrs?autoReconnect\=true&sessionVariables\=default_storage_engine\=InnoDB&useUnicode\=true&characterEncoding\=UTF-8
connection.username=openmrs

encryption.key=M3FCbvyrDxMRGclkqyD0SA\=\=
encryption.vector=/9saeTQRoNrV/NUvdu6P0g\=\=

hibernate.search.backend.analysis.configurer=luceneConfig
hibernate.search.backend.discovery.enabled=true
hibernate.search.backend.type=lucene
hibernate.search.backend.uris=http\://es\:9200

module.allow_web_admin=true