name: ci workflow
on:
  push:
    paths:
      - src/**
jobs:
  run-tests:
    name: basic job
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare docker apps environment
        run: infra/restart-docker-images.sh
      - name: Build project
        run: ./mvnw clean package
#        Обсудить откуда брать исходную openApi spec
      #- name: Run Swagger coverage
      #  if: always()
      #  run: ./swagger-coverage-commandline/bin/swagger-coverage-commandline -s http://localhost:4111/v3/api-docs -i target/swagger-coverage-output
      #- name: Check api coverage
      #  if: always()
#        run: infra/check-api-coverage.sh
      - name: Load test report history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: target/allure-results
          allure_history: allure-history
      - name: Build Swagger coverage report
        if: always()
        run: sudo cp swagger-coverage-report.html allure-history/${{ github.run_number }}
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
      - name: Clean up app environment
        if: always()
        run: pwd && ls && docker compose -f infra/docker-compose.yaml down -v
      - name: Run Checkstyle
        run: ./mvnw checkstyle:checkstyle -q
      - name: Build docker image and push to the docker hub
        if: success()
        run: infra/push-tests-in-repo.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          COMMIT_HASH: ${{ github.sha }}